menu:
    Blog: /
    Archive: /archives/
    GitHub: https://github.com/derekhe
    LinkedIn: https://cn.linkedin.com/in/sicong-he-56a95437
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo: 

# Copyright Infomation
startyear: 2000

# Font CDN
#true : use google fonts api, not stable for chinese visitor sometimes, caused by force majeure factor
#false: use useso fonts api instead of google's, great response speed for chinese visitor
googlefonts: false
